# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2.1.post124+gab47818.d20230821'
__version_tuple__ = version_tuple = (2, 1, 'gab47818.d20230821')
